// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdlFQEM2E35NFmmk41aS390JshqbRfR8o',
    appId: '1:980171789197:web:8cbf6831d333e1df6de3c4',
    messagingSenderId: '980171789197',
    projectId: 'taxiwaala',
    authDomain: 'taxiwaala.firebaseapp.com',
    databaseURL: 'https://taxiwaala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiwaala.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6xMJWwlC7RUy3dTaOutUJUo5A22G_hY',
    appId: '1:980171789197:android:0485c43e84f32e516de3c4',
    messagingSenderId: '980171789197',
    projectId: 'taxiwaala',
    databaseURL: 'https://taxiwaala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiwaala.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1yJYxD6VhatFg1GhADCpuY9ui3oosD_k',
    appId: '1:980171789197:ios:87a0f99a8f7ea3706de3c4',
    messagingSenderId: '980171789197',
    projectId: 'taxiwaala',
    databaseURL: 'https://taxiwaala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiwaala.appspot.com',
    androidClientId: '980171789197-0gqglm07soiifs0b61ljkjssvppbbchu.apps.googleusercontent.com',
    iosClientId: '980171789197-d4rkt7la9mfbjc0nga2sk70d2ctre8cr.apps.googleusercontent.com',
    iosBundleId: 'com.thexkidd.userapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1yJYxD6VhatFg1GhADCpuY9ui3oosD_k',
    appId: '1:980171789197:ios:87a0f99a8f7ea3706de3c4',
    messagingSenderId: '980171789197',
    projectId: 'taxiwaala',
    databaseURL: 'https://taxiwaala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiwaala.appspot.com',
    androidClientId: '980171789197-0gqglm07soiifs0b61ljkjssvppbbchu.apps.googleusercontent.com',
    iosClientId: '980171789197-d4rkt7la9mfbjc0nga2sk70d2ctre8cr.apps.googleusercontent.com',
    iosBundleId: 'com.thexkidd.userapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdlFQEM2E35NFmmk41aS390JshqbRfR8o',
    appId: '1:980171789197:web:5ccc31e24924f35d6de3c4',
    messagingSenderId: '980171789197',
    projectId: 'taxiwaala',
    authDomain: 'taxiwaala.firebaseapp.com',
    databaseURL: 'https://taxiwaala-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taxiwaala.appspot.com',
  );

}